# generate-config.ps1 — Generate yuzu-server.cfg with PBKDF2-SHA256 hashed credentials
#
# Usage:
#   powershell -NoProfile -ExecutionPolicy Bypass -File generate-config.ps1 `
#     -ConfigPath "C:\ProgramData\Yuzu Server\yuzu-server.cfg" `
#     -AdminUser admin -AdminPass "MyPassword123" `
#     [-OperatorUser operator -OperatorPass "OpPassword123"]
#
# Compatible with PowerShell 5.1+ (.NET Framework 4.7.2+, ships with Windows 10+)

param(
    [Parameter(Mandatory=$true)][string]$ConfigPath,
    [Parameter(Mandatory=$true)][string]$AdminUser,
    [Parameter(Mandatory=$true)][string]$AdminPass,
    [string]$OperatorUser = "",
    [string]$OperatorPass = ""
)

# Use Windows PowerShell's own modules. PSModulePath is inherited from whatever
# started the installer; started (via any intermediate process) from
# PowerShell 7, it leads 5.1 to PowerShell 7's copy of
# Microsoft.PowerShell.Security, which it cannot load, so Set-Acl below failed
# and the config file kept ProgramData's inherited permissions (#5176). Built
# without any cmdlet, so nothing here depends on the path it is fixing.
$env:PSModulePath = $PSHOME + '\Modules;' + [Environment]::GetEnvironmentVariable('PSModulePath', 'Machine')

function New-PBKDF2Entry {
    param(
        [Parameter(Mandatory=$true)][string]$Username,
        [Parameter(Mandatory=$true)][string]$Password,
        [Parameter(Mandatory=$true)][string]$Role
    )

    # 16-byte random salt
    $salt = [byte[]]::new(16)
    $rng = New-Object System.Security.Cryptography.RNGCryptoServiceProvider
    $rng.GetBytes($salt)
    $rng.Dispose()

    # PBKDF2-SHA256, 100000 iterations, 32-byte output (matches server auth.cpp)
    $pbkdf2 = New-Object System.Security.Cryptography.Rfc2898DeriveBytes(
        $Password, $salt, 100000,
        [System.Security.Cryptography.HashAlgorithmName]::SHA256
    )
    $hash = $pbkdf2.GetBytes(32)
    $pbkdf2.Dispose()

    $saltHex = -join ($salt | ForEach-Object { $_.ToString("x2") })
    $hashHex = -join ($hash | ForEach-Object { $_.ToString("x2") })

    return "${Username}:${Role}:${saltHex}:${hashHex}"
}

# Build config content
$lines = @(
    "# Yuzu Server Configuration",
    "# Version: 1",
    "# Format: username:role:salt:hash",
    "# Generated by Yuzu Server installer",
    ""
)

$lines += New-PBKDF2Entry -Username $AdminUser -Password $AdminPass -Role "admin"

if ($OperatorUser -ne "" -and $OperatorPass -ne "") {
    $lines += New-PBKDF2Entry -Username $OperatorUser -Password $OperatorPass -Role "user"
}

# The file holds the admin/operator password hashes, so it must never exist
# readable by anyone but Administrators and SYSTEM (#5176 review, #5196).
# The hashes are written only into a file that already carries a protected,
# verified Administrators+SYSTEM-only ACL, built from SIDs, not account names,
# which are translated on non-English Windows. Any failure removes what this
# run created and exits 1, and the installer then does not register the
# service. A config left by an earlier install is not touched unless this
# run fully succeeds.
$ErrorActionPreference = 'Stop'
$AdminsSid = New-Object System.Security.Principal.SecurityIdentifier('S-1-5-32-544')
$SystemSid = New-Object System.Security.Principal.SecurityIdentifier('S-1-5-18')

function Set-StrictAcl([string]$Path) {
    $acl = New-Object System.Security.AccessControl.FileSecurity
    $acl.SetAccessRuleProtection($true, $false)
    foreach ($sid in @($AdminsSid, $SystemSid)) {
        $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
            $sid, 'FullControl', 'Allow')))
    }
    [System.IO.File]::SetAccessControl($Path, $acl)
}

function Assert-StrictAcl([string]$Path) {
    $acl = [System.IO.File]::GetAccessControl($Path)
    if (-not $acl.AreAccessRulesProtected) { throw "$Path still inherits permissions" }
    $allowed = @($AdminsSid.Value, $SystemSid.Value)
    foreach ($r in $acl.GetAccessRules($true, $true, [System.Security.Principal.SecurityIdentifier])) {
        if ($allowed -notcontains $r.IdentityReference.Value) {
            throw "$Path grants access to $($r.IdentityReference.Value)"
        }
    }
}

$tmpPath = $null
$moved = $false
try {
    $parentDir = Split-Path -Parent $ConfigPath
    if ($parentDir -and -not (Test-Path -LiteralPath $parentDir)) {
        New-Item -ItemType Directory -Path $parentDir -Force | Out-Null
    }

    # Create an empty file beside the target, lock it down, verify, then write.
    $tmpPath = Join-Path $parentDir ('.yuzu-server.cfg.' + [System.Guid]::NewGuid().ToString('N') + '.tmp')
    [System.IO.File]::WriteAllBytes($tmpPath, [byte[]]@())
    Set-StrictAcl $tmpPath
    Assert-StrictAcl $tmpPath

    # Write config (UTF-8, no BOM for C++ compatibility)
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($tmpPath, $lines, $utf8NoBom)

    # A same-volume move keeps the file's own protected ACL; it replaces an
    # earlier config (and whatever ACL it had) only now that this one is ready.
    Move-Item -LiteralPath $tmpPath -Destination $ConfigPath -Force
    $tmpPath = $null
    $moved = $true
    Assert-StrictAcl $ConfigPath
} catch {
    if ($tmpPath -and (Test-Path -LiteralPath $tmpPath)) {
        Remove-Item -LiteralPath $tmpPath -Force -ErrorAction SilentlyContinue
    }
    # If the final check failed after the move, do not leave the hashes behind.
    if ($moved) {
        Remove-Item -LiteralPath $ConfigPath -Force -ErrorAction SilentlyContinue
    }
    [Console]::Error.WriteLine("Could not write a securely permissioned configuration: $($_.Exception.Message)")
    exit 1
}

Write-Host "Configuration written to: $ConfigPath"
